namespace OpenClawIntegration.Models;

public class AppSettings
{
    public CopilotSettings Copilot { get; set; } = new();
    public OpenClawSettings OpenClaw { get; set; } = new();
    public WhatsAppSettings WhatsApp { get; set; } = new();
    public SchedulerSettings Scheduler { get; set; } = new();
    public List<Topic> Topics { get; set; } = [];
}

public class CopilotSettings
{
    /// <summary>GitHub personal access token with Copilot access.</summary>
    public string Token { get; set; } = string.Empty;

    public string ApiUrl { get; set; } = "https://api.githubcopilot.com";

    /// <summary>Copilot model to use for summarisation.</summary>
    public string Model { get; set; } = "gpt-4o";

    /// <summary>Maximum tokens in each summary response.</summary>
    public int MaxTokens { get; set; } = 1000;
}

public class OpenClawSettings
{
    /// <summary>OpenClaw API key (https://openclaw.ai/).</summary>
    public string ApiKey { get; set; } = string.Empty;

    public string ApiUrl { get; set; } = "https://api.openclaw.ai";

    /// <summary>
    /// When true, summaries are generated by calling the GitHub Copilot API
    /// directly instead of routing through the OpenClaw agent endpoint.
    /// Set to true if you have not yet obtained an OpenClaw API key.
    /// </summary>
    public bool UseDirectCopilot { get; set; } = false;
}

public class WhatsAppSettings
{
    /// <summary>Twilio Account SID.</summary>
    public string AccountSid { get; set; } = string.Empty;

    /// <summary>Twilio Auth Token.</summary>
    public string AuthToken { get; set; } = string.Empty;

    /// <summary>
    /// Twilio WhatsApp-enabled sender number in E.164 format,
    /// e.g. "+14155238886" (Twilio sandbox) or your approved number.
    /// </summary>
    public string FromNumber { get; set; } = string.Empty;

    /// <summary>
    /// Recipient WhatsApp number in E.164 format, e.g. "+15551234567".
    /// </summary>
    public string ToNumber { get; set; } = string.Empty;
}

public class SchedulerSettings
{
    /// <summary>Cron expression (5-part, UTC). Default: every day at 08:00 UTC.</summary>
    public string CronExpression { get; set; } = "0 8 * * *";
}
